---
title: "R Notebook"
output: html_notebook
---



```{r}
library(dplyr)
library(glmnet)
library(ggplot2)
library(plotROC)
library(zCompositions)
```

### Load and encode the data

```{r}
load("xy.Rdata")
load("xyval.Rdata")
```

```{r}
y <- y - 1
yval <- yval - 1
```

### compute mse of various baseline models

```{r}
mse_lasso <- function(z, y, zval, yval) {
  lasso_fit <- cv.glmnet(z, y, family = "binomial", foldid = fold_id)
  lasso_pred <- predict(lasso_fit, zval, type = "response", s = "lambda.min")
  sum((lasso_pred > median(lasso_pred)) == (yval == 1)) / 202 #better accuracy
}

mse_ridge <- function(z, y, zval, yval) {
  ridge_fit <- cv.glmnet(z, y, family = "binomial", alpha = 0, foldid = fold_id)
  ridge_pred <- predict(ridge_fit, zval, type = "response", s = "lambda.min")
  sum((ridge_pred > median(lasso_pred)) == (yval == 1)) / 202 #better accuracy
}

mse_simple <- function(z, y, zval, yval) {
  z_m <- z[,19] - z[,26]
  data <- data.frame(y,z_m)
  simple_fit <- glm(y ~ z_m, data = data, family = binomial) 
  
  z_m_val <- zval[,19] - zval[,26]
  pred_data <- data.frame(yval, z_m = z_m_val)
  simple_pred <- predict(simple_fit, newdata = pred_data, type = "response")
  
  sum((simple_pred > median(simple_pred)) == (yval == 1)) / 202
}
```

### Try various imputation schemes

```{r}
z = list()
zval = list()

#simple imputation
z[[1]] = log(x + 1)
zval[[1]] = log(xval + 1)

#constant imputation
floor = min(x[x > 0])
x_prime = multRepl(x, label = 0, dl = rep(floor, ncol(x)))
x_val_prime = multRepl(xval, label = 0, dl = rep(floor, ncol(x)))
z[[2]] = as.matrix(log(x_prime))
zval[[2]] = as.matrix(log(x_val_prime))

#LN imputation
set.seed(1)
x_prime = multLN(x, label = 0, dl = rep(floor, ncol(x)))
x_val_prime = multLN(xval, label = 0, dl = rep(floor, ncol(x)), random = TRUE)
z[[3]] = as.matrix(log(x_prime))
zval[[3]] = as.matrix(log(x_val_prime))
```

### Compare predictive performance of various baseline methods

```{r}
set.seed(555)
mse = matrix(0, nrow = length(z), ncol = 3)
for(i in 1:length(z)) {
  print(i)
  mse[i, 1] = mse_lasso(z[[i]], y, zval[[i]], yval)
  mse[i, 2] = mse_ridge(z[[i]], y, zval[[i]], yval)
  mse[i, 3] = mse_simple(z[[i]], y, zval[[i]], yval)
}

mse
```