---
title: "R Notebook"
output: html_notebook
---

```{r}
library(glmnet)
library(ggplot2)
library(gridExtra)
library(MASS)
library(leaps)
library(dplyr)
library(magrittr)
source("two_step.r")
source("two_step_cv.r")
source("logRatioLasso.R")
source("approximate_fs.r")
source("cv_fs.r")
```


We compare FS and approximate FS in terms of runtime and MSE.

## Runtime simulation

We compare the runtime of naive lasso, constrained lasso, approximate FS, and FS (not including CV).  For FS and approximate FS, we choose 50 features max.  For naive lasso and constrained lasso we fit the whole path.

Setting
n = 500
p = 100, 500, 1000

### Manual exploration

```{r}
n <- 500
p <- 200
k_max <- 10

c <- 0
sigma <- autoRegressiveCorr(p, c)
beta <- c(2,-2,1,-1, rep(0, p-4))
X  <- abs(mvrnorm(n = n, rep(0, p), sigma))
x <- X
z <- log(X)
z <- scale(z, center = TRUE, scale = FALSE)
y <- z %*% beta * sig + rnorm(n)
y <- y - mean(y)


#fs
t1 <- Sys.time()
w <- small_to_big_z(z, 1:p)
fs_model <- regsubsets(w, y, method = "forward", nvmax = k_max, intercept = TRUE)
t2 <- Sys.time()
t2 - t1

#approx fs
t1 <- Sys.time()
approx_fs_model <- approximate_fs(z, y, k_max = k_max)
t2 <- Sys.time()
t2 - t1

#naive enumeration lasso
t1 <- Sys.time()
w <- small_to_big_z(z, 1:p)
lasso_model <- glmnet(w, y, intercept = FALSE)
t2 <- Sys.time()
t2 - t1

#constrained lasso
t1 <- Sys.time()
constrained_lasso_model <- glmnet.constr(z, y)
t2 <- Sys.time()
t2 - t1

```

### Systemic wrapper

```{r}
sim_wrapper <- function(n, p, method = c("fs", "approx_fs", "lasso", "constrained_lasso"), k_max = 10, c = 0) {

  sigma <- autoRegressiveCorr(p, c)
  beta <- c(2,-2,1,-1, rep(0, p-4))
  X  <- abs(mvrnorm(n = n, rep(0, p), sigma))
  x <- X
  z <- log(X)
  z <- scale(z, center = TRUE, scale = FALSE)
  y <- z %*% beta * sig + rnorm(n)
  y <- y - mean(y)
  
  
  #fs
  if(method == "fs") {
    t1 <- Sys.time()
    w <- small_to_big_z(z, 1:p)
    fs_model <- regsubsets(w, y, method = "forward", nvmax = k_max, intercept = TRUE)
    t2 <- Sys.time()
  }
  
  #approx fs
  if(method == "approx_fs") {
    t1 <- Sys.time()
    approx_fs_model <- approximate_fs(z, y, k_max = k_max)
    t2 <- Sys.time()
  }
  
  #naive enumeration lasso
  if(method == "lasso") {
    t1 <- Sys.time()
    w <- small_to_big_z(z, 1:p)
    lasso_model <- glmnet(w, y, intercept = FALSE)
    t2 <- Sys.time()
  }

  #constrained lasso
  if(method == "constrained_lasso") {
    t1 <- Sys.time()
    constrained_lasso_model <- glmnet.constr(z, y)
    t2 <- Sys.time()
  }

  return(c(method, n, p, c, k_max, t2 - t1))
}

sim_wrapper(500, 500, method = "lasso")
```

### Systemic simulations

```{r}
n <- 500
k_max <- 10
c <- 0
n_reps <- 10

sim_data <- data.frame(stringsAsFactors = FALSE)

for(p in c(30, 50, 75, 100, 150)) {
  for(rep in 1:n_reps) {
    temp <- sim_wrapper(n, p, method = "fs")
    print(paste0("run complete:",p," at ", Sys.time()))
    sim_data <- rbind(sim_data, temp, stringsAsFactors = FALSE)
  }
}

for(p in c(30, 50, 75, 100, 150, 200)) {
  print(p)
  for(rep in 1:n_reps) {
    temp <- sim_wrapper(n, p, method = "approx_fs")
    print(paste0("run complete:",p," at ", Sys.time()))
    sim_data <- rbind(sim_data, temp, stringsAsFactors = FALSE)
  }
}
```

```{r}
save(sim_data, file = "sims/runtime-sims/fs-runtime.RData")
```

```{r}
sim_data <- data.frame(stringsAsFactors = FALSE)

for(p in c(50, 100, 500, 1000, 2000)) {
  print(p)
  for(rep in 1:n_reps) {
    temp <- sim_wrapper(n, p, method = "lasso")
    print(paste0("run complete:",p," at ", Sys.time()))
    sim_data <- rbind(sim_data, temp, stringsAsFactors = FALSE)
  }
}

for(p in c(50, 100, 500, 1000, 2000)) {
  print(p)
  for(rep in 1:n_reps) {
    temp <- sim_wrapper(n, p, method = "constrained_lasso")
    print(paste0("run complete:",p," at ", Sys.time()))
    sim_data <- rbind(sim_data, temp, stringsAsFactors = FALSE)
  }
}

names(sim_data) <- c("method", "n", "p", "corr", "k_max", "time")
save(sim_data, file = "sims/runtime-sims/lasso-runtime.RData")
```

```{r}
load(file = "sims/runtime-sims/lasso-runtime.RData")
sim_data$time <- as.numeric(sim_data$time)
sim_data$p <- as.numeric(sim_data$p)
sim_data$time[sim_data$method == "lasso" & sim_data$p == 2000] <-
  sim_data$time[sim_data$method == "lasso" & sim_data$p == 2000] * 60
sim_data$method[sim_data$method == "constrained_lasso"] <- "lr_lasso"

lasso_plot <- ggplot(sim_data, aes(x = p, y = time, color = method, 
                                   group = interaction(method,as.factor(p)))) + 
                       geom_boxplot(outlier.shape = NA, width = 100, position = "identity") +
  labs(x = "Dimension", y = "Runtime (s)") +
  geom_line(data = sim_data %>% group_by(method, p) %>% summarise(time = median(time)),
            mapping = aes(x = p, y = time, color = method, group = method),
            linetype = "dotted")

lasso_plot
```

```{r}
ggsave(lasso_plot, file = "plots/runtime/lasso-runtime.pdf", device = "pdf", height = 3.5)
```

```{r}
gg_color_hue <- function(n) {
  hues = seq(15, 375, length = n + 1)
  hcl(h = hues, l = 65, c = 100)[1:n]
}
colors <- gg_color_hue(2)

load(file = "sims/runtime-sims/fs-runtime.RData")
sim_data$time <- as.numeric(sim_data$time)
sim_data$p <- as.numeric(sim_data$p)
sim_data$time[sim_data$method == "fs" & sim_data$p == 150] <- 
  sim_data$time[sim_data$method == "fs" & sim_data$p == 150] * 60

fs_plot <- ggplot(sim_data, aes(x = p, y = time, color = method, 
                                   group = interaction(method,as.factor(p)))) + 
                       geom_boxplot(outlier.shape = NA, width = 8, position = "identity") +
  scale_color_manual(values = colors[2:1]) +
  labs(x = "Dimension", y = "Runtime (s)") +  
  geom_line(data = sim_data %>% group_by(method, p) %>% summarise(time = median(time)),
            mapping = aes(x = p, y = time, color = method, group = method),
            linetype = "dotted")
fs_plot
```

```{r}
ggsave(fs_plot, file = "plots/runtime/fs-runtime.pdf", device = "pdf", height = 3.5)
```

```{r}
joint_plot <- grid.arrange(fs_plot, lasso_plot, ncol = 2)
```

```{r}
ggsave(file = "plots/runtime/joint-runtime.pdf", plot = joint_plot,
       device = "pdf", width = 5.5, height = 1.6, units = "in")
ggsave(file = "plots/runtime/joint-runtime.eps", plot = joint_plot,
       device = "eps", width = 5.5, height = 1.6, units = "in")
```